name: download actions artifact from prev workflow
on: workflow_dispatch
jobs:
  download-hello-world:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: list artifacts from repo
        run: |
          gh api repos/shawnHartsell/actions-playground/actions/artifacts
      
      # https://cli.github.com/manual/gh_run_download
      # repo has to be present
      # alternatively, gh api can be used as well as curl
      - name: download hello-world artifact
        run: |
          gh run download 5942149259 --repo shawnHartsell/actions-playground --dir artifacts
          ls
          cd artifacts
          ls
          cat hello-world.txt

        
          
         
