name: download actions artifact from prev workflow
on: workflow_dispatch
jobs:
  download-hello-world:
    runs-on: ubuntu-latest
    steps:
      - name: download hello-world with curl
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          curl -L -v \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $GH_TOKEN" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/shawnHartsell/actions-playground/actions/artifacts/877227176/zip
