name: download actions artifact from prev workflow
on: workflow_dispatch
jobs:
  download-hello-world:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: list artifacts from repo
        run: |
          gh api repos/shawnHartsell/actions-playground/actions/artifacts
      
      - name: download hello-world artifact
        run: |
          gh api repos/shawnHartsell/actions-playground/actions/artifacts/877227176/zip
      
      - name: unzip the artifact and print contents
        run: |
          unzip hello-world.zip
          ls -l
          cat hello-world.txt

        
          
         
