name: Envrionment example

on:
  workflow_dispatch:
jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: 
      name: production
      url: https://github.com
    steps:
      - name: deploy
        run: echo "hello!"
