name: workflow dispatch
on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        default: 'warning'
        type: choice
        options:
          - info
          - warning
          - debug
        required: true
      print_tags:
        description: 'True to print to STDOUT'
        type: boolean
      tags:
        description: 'Test scenario tags'
        type: string
      environment:
        description: 'Environment to run tests against'
        type: environment
      app-to-deploy:
        description: 'field with bad type'
        type: deployment-bundle
      app-to-deploy1:
        type: deployment-bundle
      
jobs:
  dump-event:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
