name: workflow dispatch
on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        default: 'warning'
        type: choice
        options:
          - info
          - warning
          - debug
      print_tags:
        description: 'True to print to STDOUT'
        type: boolean
      tags:
        description: 'Test scenario tags'
        type: string
      environment:
        description: 'Environment to run tests against'
        type: environment
      bad-field:
        description: 'field with bad typet'
        type: taco
      bad-field1:
        description: 'field with bad typet'
        type: taco
      bad-field2:
        description: 'field with bad typet'
        type: taco
      bad-field3:
        description: 'field with bad typet'
        type: taco
      bad-field4:
        description: 'field with bad typet'
        type: taco
      bad-field5:
        description: 'field with bad typet'
        type: taco
      bad-field6:
        description: 'field with bad typet'
        type: taco
      
jobs:
  dump-event:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
